version: '3'

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

    honeypot:
      build: 
        context: .
        dockerfile: Dockerfile
      image: honeypot:latest
      restart: always
      depends_on:
        - db
